name: Deploy to EC2 using AWS CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip the application
        run: zip -r myapp.zip .

      - name: Upload to S3
        run: aws s3 cp myapp.zip s3://dev-codedeploy-bucket-ajkgr8mu/myapp.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name MyCodeDeployApp \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name MyDeploymentGroup \
            --s3-location bucket=dev-codedeploy-bucket-ajkgr8mu,bundleType=zip,key=myapp.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2